### ISSUE TITLE
The code seems incomplete.

### ISSUE THREAD

**Issue by yezanting** [Cocofeat/TBraTS#1]
I am very sorry to disturb you, and thank you very much for your sharing. I tried to reproduce the method of your paper, but when I understood the code, I found that the code you published was not complete and there was something missing.

**Comment by Cocofeat** [comment]
Thanks for your attention. Currently, we only release the main part of it. We will release all of the codes after the camera-ready DLL.

**Comment by Cocofeat** [comment]
Thanks for your attention. Currently, we only release the main part of it. We will release all of the codes after the camera-ready DDL.
