### ISSUE TITLE
Calculating Dice loss

### ISSUE THREAD

**Issue by HussainAlasmawi** [Cocofeat/TBraTS#6]
Dear Author,

I'm not sure how the dice score is calculated. Right now, from the code, as I can see, after we get alpha from below then, we are using  dce_eviloss function
![image](https://user-images.githubusercontent.com/91467092/202857185-fef1e0bb-a82f-4327-b73e-c91b48cc073e.png)
which is defined below (for the dice part)
![image](https://user-images.githubusercontent.com/91467092/202857252-98366279-dfec-4fdf-ba02-e00188c90f96.png)

but the softmax_dice does not use any softmax
![image](https://user-images.githubusercontent.com/91467092/202857301-c58e15e9-90a1-47d5-98e2-d4e3386b95e9.png)
![image](https://user-images.githubusercontent.com/91467092/202857675-bcd8db78-2930-4cde-9222-ffe5a77dce4b.png)
and it takes predictions as alpha which is evidence+1 which is getting after applying softplus. This means we are trying to fit [0, infinity] input into the dice equation, not the [0,1] interval input which leads to negative loss sometimes. I believe there is something have been missed.

I hope it was clear and it will be fixed soon.

Thanks,

**Comment by Cocofeat** [comment]
Yes, we did not use softmax_dice. If softmax is used, it may cause an over-confident situation. There is a problem with the function definition here, sorry for the interference.
The calculation of dice loss will be further studied in subsequent versions.
