### ISSUE TITLE
Trouble on uncertainty calculation

### ISSUE THREAD

**Issue by noteless517** [Cocofeat/TBraTS#8]
I'm sorry to bother you.  I'm glad to further develop your creative work but I meet trouble when running your code, I can't found the function "UncertaintyAndCorrectionEvalNumpy" and the "test_uncertainty" you use in the code but the ece_binary function in the numpyfunctions.py, I don't understand how to make the model work, would you like to help me?

**Comment by Cocofeat** [comment]
Sorry for confusing you, we have already uploaded this file. In addition, more details can refer to the following two directories:
[UMIS](https://github.com/Cocofeat/UMIS)
[Assessing Reliability and Challenges of Uncertainty Estimations for Medical Image Segmentation](https://github.com/alainjungo/reliability-challenges-uncertainty)

**Comment by noteless517** [comment]
Thanks a lot!!
